# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaketoGo < Formula
  desc "A tiny helper utility to make access to servers eaiser for different projects and environments."
  homepage "https://github.com/ivan-leschinsky/taketo-go"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.0/taketo-darwin-amd64", using: :nounzip
      sha256 "e18db321e6b77be3726d08b4f27a9c69e1a652d73ef46966087826fd3ce4a83f"

      def install
        bin.install "taketo-darwin-amd64" => "taketo-go"
      end
    end
    on_arm do
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.0/taketo-darwin-arm64", using: :nounzip
      sha256 "848d4ffcac3fd1f40e1c8de7909a540575408c6a2dbe946a8be2d375f33db76d"

      def install
        bin.install "taketo-darwin-arm64" => "taketo-go"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.0/taketo-linux-amd64", using: :nounzip
        sha256 "b4447ba5b7d721f779ae9d02eeadade384fb965e15b75789551d25a58a7274e7"

        def install
          bin.install "taketo-linux-amd64" => "taketo-go"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.0/taketo-linux-arm", using: :nounzip
        sha256 "31ff5424ee81ccc50dcf7d8067bdb4ea0345e16f0f238d02c386cd76d065a227"

        def install
          bin.install "taketo-linux-arm" => "taketo-go"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.0/taketo-linux-arm64", using: :nounzip
        sha256 "af4fc5679f5ee9c8159be91f70869ed1d9efed88878bb313236125cc25c9ce97"

        def install
          bin.install "taketo-linux-arm64" => "taketo-go"
        end
      end
    end
  end

  test do
    system "#{bin}/taketo-go --version"
  end
end
