# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaketoGo < Formula
  desc "A tiny helper utility to make access to servers eaiser for different projects and environments."
  homepage "https://github.com/ivan-leschinsky/taketo-go"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.2/taketo-darwin-amd64", using: :nounzip
      sha256 "399f1c113a117f323fb2d1818f148e26bf5cb1675697e37b345245cbcb8527be"

      def install
        bin.install "taketo-darwin-amd64" => "taketo-go"
      end
    end
    on_arm do
      url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.2/taketo-darwin-arm64", using: :nounzip
      sha256 "eff1bd1f6f2dd3f7328ffcbc2115a90ee35ea61322851d8c5eba69b038347e55"

      def install
        bin.install "taketo-darwin-arm64" => "taketo-go"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.2/taketo-linux-amd64", using: :nounzip
        sha256 "20557dde9c75c753358e8bde4c33c351dbaa6c8f6e12e0c215c1fc63a5a3d565"

        def install
          bin.install "taketo-linux-amd64" => "taketo-go"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.2/taketo-linux-arm", using: :nounzip
        sha256 "597a1004aabc79c6af9cd67ac8213c0749eeb1300b71dc1516c16c60a4b1c826"

        def install
          bin.install "taketo-linux-arm" => "taketo-go"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ivan-leschinsky/taketo-go/releases/download/v0.1.2/taketo-linux-arm64", using: :nounzip
        sha256 "bc403f08cdfe4c54f3ab12249e9acfa74d19e583f7a32e1b915f48aa3a047116"

        def install
          bin.install "taketo-linux-arm64" => "taketo-go"
        end
      end
    end
  end

  test do
    system "#{bin}/taketo-go --version"
  end
end
